export const URL = 'http://10.0.2.2:80/Asmeniniai/fastshop/backend/laravel/public/api';
// export const URL = 'http://192.168.0.102/2019%20Reproduction/fastshop/backend/laravel/public/api';

//General
export const LOADING_DATA = 'LOADING_DATA';
export const DATA_LOADED = 'DATA_LOADED';
export const GET_ALL_DATA = 'GET_ALL_DATA';
export const DATA_LOADED_ERROR = 'DATA_LOADED_ERROR';
export const DATA_LOAD_CANCELED = 'DATA_LOAD_CANCELED';

// FOR CATEGORIES

export const LOADING_GET_CATEGORIES = 'LOADING_GET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const REMOVE_GET_CATEGORIES_ERR = 'REMOVE_GET_CATEGORIES_ERR';
export const LOADING_POST_CATEGORY = 'LOADING_POST_CATEGORY';
export const POST_CATEGORY = 'POST_CATEGORY';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';
export const LOADING_EDIT_CATEGORY = 'LOADING_EDIT_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';
// FOR SUBCATEGORIES

export const LOADING_GET_SUBCATEGORIES = 'LOADING_GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES_APPEND = 'GET_SUBCATEGORIES_APPEND';
export const GET_SUBCATEGORIES_ERROR = 'GET_SUBCATEGORIES_ERROR';
export const REMOVE_GET_SUBCATEGORIES_ERR = 'REMOVE_GET_SUBCATEGORIES_ERR';
export const FRW_TO_SUBCATEGORIES = 'FRW_TO_SUBCATEGORIES';
export const LOADING_POST_SUBCATEGORY = 'LOADING_POST_SUBCATEGORY';
export const  LOADING_EDIT_SUBCATEGORY = ' LOADING_EDIT_SUBCATEGORY';
export const POST_SUBCATEGORY = 'POST_SUBCATEGORY';
export const POST_SUBCATEGORY_ERROR = 'POST_SUBCATEGORY_ERROR';
export const LOADING_SUBCATEGORY = 'LOADING_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const EDIT_SUBCATEGORY_ERROR = 'EDIT_SUBCATEGORY_ERROR';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const DELETE_SUBCATEGORY_ERROR = 'DELETE_SUBCATEGORY_ERROR';

// FOR PRODUCTS

export const LOADING_GET_PRODUCTS = 'LOADING_GET_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_APPEND = 'GET_PRODUCTS_APPEND';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const REMOVE_GET_PRODUCTS_ERROR = 'REMOVE_GET_PRODUCTS_ERROR';
export const UNMOUNT_PRODUCTS = 'UNMOUNT_PRODUCTS';
export const LOADING_GET_PRODUCT= 'LOADING_GET_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';;
export const LOADING_POST_PRODUCT = 'LOADING_POST_PRODUCT';
export const POST_PRODUCT = 'POST_PRODUCT';
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR';
export const LOADING_EDIT_PRODUCT = 'LOADING_EDIT_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const SAVE_COMBINATION = 'SAVE_COMBINATION';
export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';
export const GET_LIKED_PRODUCTS = 'GET_LIKED_PRODUCTS';
export const GET_LIKED_PRODUCTS_ERROR = 'GET_LIKED_PRODUCTS_ERROR';

// FOR AUTHENTICATION

export const SAVE_USER = 'SAVE_USER';
export const TRY_LOG_IN = 'TRY_LOG_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_FAILED = 'LOG_OUT_FAILED';

//FOR COMPARISON

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
export const COMPARE_RESULT = 'COMPARE_RESULT';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SORT_ARRAY = 'SORT_ARRAY';
export const GO_TO_LIST = 'GO_TO_LIST';
export const CLEAR_RESULTS_TRIGGERED = 'CLEAR_RESULTS_TRIGGERED';
export const CLEAR_SELECTED_ARRAY = 'CLEAR_SELECTED_ARRAY';