export const URL = 'http://10.0.2.2:80/2019%20Reproduction/fastshop/backend/laravel/public/api';
// export const URL = 'http://192.168.0.102/2019%20Reproduction/fastshop/backend/laravel/public/api';

// FOR CATEGORIES

export const LOADING_GET_CATEGORIES = 'LOADING_GET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const GET_CATEGORY = 'GET_CATEGORY';
export const POST_CATEGORY = 'POST_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// FOR SUBCATEGORIES

export const LOADING_GET_SUBCATEGORIES = 'LOADING_GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES_ERROR = 'GET_SUBCATEGORIES_ERROR';
export const UNMOUNT_SUBCATEGORIES = 'UNMOUNT_SUBCATEGORIES';
export const FRW_TO_SUBCATEGORIES = 'FRW_TO_SUBCATEGORIES';
export const POST_SUBCATEGORY = 'POST_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';

// FOR PRODUCTS

export const LOADING_GET_PRODUCTS = 'LOADING_GET_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const UNMOUNT_PRODUCTS = 'UNMOUNT_PRODUCTs';
export const GET_PRODUCT = 'FRW_TO_PRODUCTS';
export const POST_PRODUCT = 'POST_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// FOR AUTHENTICATION

export const TRY_LOG_IN = 'TRY_LOG_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_FAILED = 'LOG_OUT_FAILED';

//FOR COMPARISON

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
export const COMPARE_RESULT = 'COMPARE_RESULT';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SORT_ARRAY = 'SORT_ARRAY';
export const GO_TO_LIST = 'GO_TO_LIST';
export const CLEAR_RESULTS_TRIGGERED = 'CLEAR_RESULTS_TRIGGERED';
export const CLEAR_SELECTED_ARRAY = 'CLEAR_SELECTED_ARRAY';